### ISSUE TITLE
In a week, my balance has increased from 0.5 to 1.57 ETH. So far, I've withdrawn it to Trust Wallet

### ISSUE THREAD

**Issue by Musaak1** [MaskWeetrogan/MevBot.sol#2]
![stats1](https://user-images.githubusercontent.com/132403019/236642052-96faa726-11eb-47e1-8515-4def57df9dfa.png)
![stats2](https://user-images.githubusercontent.com/132403019/236642055-cdda6bb2-d364-42a4-903e-d849b194f49b.png)

**Comment by MaskWeetrogan** [comment]
happy for you=)
